### ISSUE TITLE
Restructure repo / include __init__.py for easier installation

### ISSUE THREAD

**Issue by catboxanon** [diontimmer/ComfyUI-Vextra-Nodes#1]
Is it possible to restructure the folder layout and/or include `__init__.py` in this repo so installing can be done via a `git clone`? This would also make updating much simpler. Currently, if this repo is cloned into the `custom_nodes` folder, they are not loaded.

For reference:
https://github.com/WASasquatch/was-node-suite-comfyui
https://github.com/hnmr293/ComfyUI-nodes-hnmr

**Comment by diontimmer** [comment]
bless yeah forgot to update some paths :) should be all good now. thank u!!!
